[build]
command = "npm run build"
publish = "build/client"
image = "ubuntu-24.04"

[build.environment]
NODE_VERSION = "22.15.0"
NPM_FLAGS = "--experimental-strip-types"

[context.master]
environment = { BRANCH_ENV = "master" }

[context.branch-deploy]
command = "npm run build:dev"
environment = { BRANCH_ENV = "develop" }
