[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/assets/*, /*.{svg,png,jpg,jpeg,woff,woff2,ttf,eot,otf}"
[headers.values]
Cache-Control = "max-age=31536000, public"

[build]
command = "npm run build"
publish = "build"
